version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/gimmepm/gimme
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go get -u golang.org/x/lint/golint
      - run: golint -set_exit_status ./...
      - run: go test -v ./...
      - run: make test
  deliver:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/gimmepm/gimme
    steps:
      - checkout
      - run: go get -v -t -d ./...

        # Install and run dep
      - run: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run: dep ensure

      - setup_remote_docker:
          docker_layer_caching: true
      - run: make docker

        # Login to docker hub and push the image
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run: docker push gimmepm/gimme

workflows:
  version: 2
  build_and_deliver:
    jobs:
      - build
      - deliver:
          requires:
            - build
