version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/gimmepm/gimme
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go get -u golang.org/x/lint/golint
      - run: golint -set_exit_status ./...
      - run: go test -v ./...
      - run: make test
  deploy:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/gimmepm/gimme
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: make docker

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
