version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/gimmepm/gimme
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go get -u golang.org/x/lint/golint
      - run: golint -set_exit_status ./...
      - run: go test -v ./...
      - run: make test
      - run: make docker
      - run: docker push gimmepm/gimme
